services:
  web:
    build:
      context: ..
      dockerfile: Docker/web.Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www/html
    depends_on:
      - db
    
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: semantiqai
    ports:
      - "3306:3306"
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db