services:
  web:
    container_name: api
    build:
      context: ..
      dockerfile: Docker/web.Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "/usr/local/bin/wait-for-it.sh db:3306 -s -t 60 -- composer install && php artisan migrate --force && apache2-foreground"
    
  db:
    container_name: db
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: semantiqai
    ports:
      - "3306:3306"
    networks:
      - app-network
    
  phpmyadmin:
    container_name: admin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

  node:
    container_name: node
    build:
      context: ..
      dockerfile: Docker/node.Dockerfile
    ports:
      - "5173:5173"
      - "4173:4173"
    volumes:
      - ../frontend:/app
    working_dir: /app
    command: sh -c "npm run dev & tail -f /dev/null"
    networks:
      - app-network

  # linux:
  #   container_name: linux
  #   build:
  #     context: ..
  #     dockerfile: Docker/linux.Dockerfile
  #   ports:
  #     - "11434:11434"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge